name: Trigger auto deployment for aca-delete-test

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/aca-delete-test-AutoDeployTrigger-efd79c1a-d62c-44a2-9c7c-bc1777c8d7f0.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ACADELETETEST_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ACADELETETEST_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ACADELETETEST_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: vijillapublishcr.azurecr.io
          registryUsername: ${{ secrets.ACADELETETEST_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ACADELETETEST_REGISTRY_PASSWORD }}
          containerAppName: aca-delete-test
          resourceGroup: func-aca-delete-mrg-test
          imageToBuild: vijillapublishcr.azurecr.io/aca-delete-test:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


